######################################################################
##
## Filename: test_uart.udo
## Created on: Fri Nov 06 9:26:43 AM Iran Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
